image: node:latest

stages:
  - ver
  - init
  - tests
  - deploy

ver:
  stage: ver
  script:
    - node --version
    - whoami
init:
  stage: init
  script:
    - npm cache verify
    - rm -rf node-modules
    - npm install

deploy_production:
  stage: deploy
  script:
    - git push heroku master
    - echo "Deployed to production server"
  environment:
    name: production
    url: https://spork-bot.herokuapp.com/
  when: manual
  only:
    - master