image: node:latest

stages:
  - ver
  - init
  - lint
  - tests
  - deploy

ver:
  stage: ver
  script:
    - node --version
    - whoami

init:
  stage: init
  script:
    - npm cache verify
    - rm -rf node-modules
    - npm install
clean_code:
  stage: lint
  script:
    - npm test

run_tests:
  stage: tests
  script:
    - npm test

deploy_production:
  stage: deploy
  script:
    - git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/spork-bot.git
    - git push heroku master
    - echo "Deployed to production server"
  environment:
    name: production
    url: https://spork-bot.herokuapp.com/
  when: manual
  only:
    - master