image: node:latest

stages:
  - ver
  - init
  - run_lint
  - tests
  - deploy

ver:
  stage: ver
  script:
    - node --version
    - whoami
init:
  stage: init
  script:
    - npm cache verify
    - rm -rf node-modules
    - npm install
run_lint:
  stage: run_lint
  script:
    # install eslint
    - npm i eslint
    # Run eslint
    - node_modules/eslint/bin/eslint.js .
deploy_production:
  stage: deploy
  image: ruby:latest
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=spork-bot --api-key=$HEROKU_API_KEY
    - echo "Deployed to production server"
  environment:
    name: production
    url: https://spork-bot.herokuapp.com/
  when: manual
  only:
    - master