version: '3'

services:
  sporkbot:
    build:
      context: .
      dockerfile: Dockerfile
    image: sporkbot
    container_name: sporkbot
    restart: unless-stopped
    env_file: .env
    environment:
      - TOKEN=$TOKEN
      - PREFIX=$PREFIX
      - AUTHOR=$AUTHOR
      - YOUTUBEKEY=$YOUTUBEKEY
      - DEVGUILD=$DEVGUILD
    volumes:
      - .:/home/node/app
      - node_modules:/home/node/app/node_modules
      - resources:/home/node/app/resources

volumes:
  node_modules:
    resources: